config/routes.rb
Rails.application.routes.draw do

  root 'sessions#home'

  get '/signup' => 'users#new'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get '/most_popular_teacher' => 'users#most_popular'

  get '/auth/:provider/callback' => 'sessions#create'
  resources :users
  # , only: [:create, :new, :show]
  resources :courses do
    resources :grades
    # , only: [:new, :index, :show, :create]
      # :edit, :show]
  end
  resources :students do
    resources :grades, only: [:show, :index]
  end
  resources :grades
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/grade.rb
class Grade < ApplicationRecord
  belongs_to :student
  belongs_to :course

  validates :value, numericality: {only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 100}
  validates :comment, presence: true

   def student_attributes=(student_params)
      student = Student.find_or_create_by(student_params)
      self.student = student if student.valid? || !self.student
   end

end

app/controllers/grades_controller.rb
class GradesController < ApplicationController
before_action :set_grade, only: [:show, :edit, :update, :destroy]

  def new
    @students = Student.all
    @course = Course.find_by_id(params[:course_id])
    @grade = @course.grades.build
  end

  def create
    @grade = Grade.new(grade_params)
    @course = Course.find_by_id(params[:course_id])
    if @grade.save
#       Adding json
#      respond_to do |f|
#         f.html {redirect_to grade_path(@grade)}
#         f.json {render :json => @grade}
#      end


        redirect_to grade_path(@grade)
    else
        @students = Student.all
        render :new
      end
    end


#  Showing individual grade

    def show
     @course = Course.find_by_id(@grade.course_id)
    end

    def index
        @students = Student.all
        if @course = Course.find_by_id(params[:course_id])
            @grades = @course.grades.order(:student_id)
        else
            @grades = Grade.all
        end
    end


    def edit
      @course = Course.find_by_id(params[:id])
      @student = Student.find_by_id(@grade.student_id)
    end

    def update
      @grade.update(grade_params)
      @grade.save
      redirect_to grade_path(@grade)
    end

    def destroy
      @grade.destroy
      redirect_to grades_path
    end

    private

    def set_grade
        @grade = Grade.find_by(id: params[:id])
        if !@grade
          redirect_to grades_path
        end
      end


    def grade_params
        params.require(:grade).permit(:value, :comment, :student_id, :course_id, student_attributes: [:first_name, :last_name])
    end

end

app/helpers/grades_helper.rb
module GradesHelper
end

app/views/grades/_errors.html.erb
<% if @grade.errors.any? %> 
 <div id="error_explanation"> 
   <h2><%= pluralize(@grade.errors.count, "error") %> prohibited this grade from being saved:</h2>  
   <ul> 
       <% @grade.errors.full_messages.each do |message| %> 
       <li><%= message %></li> 
        <% end %> 
   </ul> 
 </div> 
<% end %> 

app/views/grades/_form.html.erb
<%= form_for(@grade) do |f|%>

<%= render partial: 'layouts/errors', locals: {object: @grade} %>
  <!-- f.hidden_field :course_id, :value => @course.id %>  %> -->
<div>
  <%= f.label :student_id, "Select a Student" %>
  <%= f.collection_select :student_id, Student.alpha, :id, :last_name %>

</div>
<br>
<div>
     <%= f.label :value %>
     <%= f.number_field :value, min:0, max:100 %>
</div>
<br></br>
<div>
  <%= f.label :comment %>
  <%= f.text_field :comment%>
</div>

<%= f.submit %>
<% end %>

app/views/grades/edit.html.erb
<h2> Edit Grade </h2>
<%= render 'form' %>

app/views/grades/index.html.erb
<h3>Course: <%= @course.coursename %></h3>

<table class='table table-bordered'>
  <thead>
    <tr>
      <th style="width:300px;">Student </th>

      <th style="width:50px;">Grade</th>
      <th >Comment</th>
    </tr>
  </thead>
  <tbody>
    <% @students.alpha.each do |student| %>
      <tr>
         <td><%= student.last_name %> ,<%= student.first_name%></td>
         <% grade=student.grades.find_by course_id: @course.id %>
          <% if grade %>
            <td> <%= grade[:value] %> </td>
            <td> <%= grade[:comment]%> </td>
          <% else %>
              <td> NG </td>
              <td> No Comment </td>
          <% end %>
      </tr>
    <% end %>

  </tbody>
</table>
<% if @course.user == current_user %>
<p> *** NOTE *** Once all the grades are done the course will be CONCLUDED </p>
<p>



    <% if @course.grades.count < @students.count %>
        <%= link_to "Enter Grade/Comment", new_course_grade_path(@course) %></button>
          <button class="btn btn-outline-primary">

    <% end %>



</p>

<% end %>

app/views/grades/new.html.erb
<h2>Enter Grades </h2>
<%= render partial: "layouts/errors", locals: { object: @grade } %>


<%= form_for([@course, @grade]) do |f|%>
<table class='table table-bordered'>
  <thead>
    <tr>
      <th style="width:300px;">Student </th>

      <th style="width:50px;">Grade</th>
      <th >Comment</th>
    </tr>
  </thead>
  <tbody>

    <% @students.alpha.each do |student| %>
      <tr>
         <td><%= student.last_name %> ,<%= student.first_name%></td>
           <% grade=student.grades.find_by course_id: @course.id %>
            <% if grade %>
              <td> <%= grade[:value] %> </td>
              <td> <%= grade[:comment]%> </td>
           <% else %>

              <td> NG </td>
              <td> No Comment </td>
          <% end %>
      </tr>
    <% end %>

  </tbody>
</table>


    <%= f.hidden_field :course_id, :value => @course.id %>

      <%= f.label :student_id, "Enter Grade for " %>
      <%= f.collection_select :student_id, Student.alpha, :id, :last_name  %>


       <%= f.label :value %>
       <%= f.number_field :value, min:0, max:100 %>

  <br></br>

    <%= f.label :comment %>
    <%= f.text_field :comment %>
  


<%= f.submit %>
<% end %>

app/views/grades/show.html.erb
<h3> Here is the grade for: <%= @grade.student.last_name%>, <%= @grade.student.first_name%> </h3>
<br></br>

<h3>Course: <%= @course.coursename %>: </h3>
<br></br>
<div>
  <h4>Grade: <%= @grade.value%> </h4>
  <h4>Comment: "<%= @grade.comment%>" </h4>
</div>

<% if @course.user == current_user %>
<p>




        <%= link_to "Back to Course", course_grades_path(@course) %></button>
    <button class="btn btn-outline-primary">

      <%= link_to "Edit Grade", edit_grade_path(@grade) %></button>
      <button class="btn btn-outline-primary">


</p>

<% end %>
 <!-- link_to "Delete Grade", grade_path(@grade), data: { confirm: 'Are you sure?' }, method: :delete  %></button> -->
<!-- <button class="btn btn-outline-primary"> -->