config/routes.rb
Rails.application.routes.draw do

  root 'sessions#home'

  get '/signup' => 'users#new'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get '/most_popular_teacher' => 'users#most_popular'

  get '/auth/:provider/callback' => 'sessions#create'
  resources :users
  # , only: [:create, :new, :show]
  resources :courses do
    resources :grades
    # , only: [:new, :index, :show, :create]
      # :edit, :show]
  end
  resources :students do
    resources :grades, only: [:show, :index]
  end
  resources :grades
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.erb
<% if object.try(:errors).try(:any?) %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>

    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_errors1.html.erb
<ul>


    <% flash.each do |key, value| %> 
      <div><%= value %></div> 
    <% end %> 
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>


    <title>Gradelink</title>


  <body>

    <% flash.each do |key, value| %> 
      <div><%= value %></div> 
    <% end %> 

   <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          <a class="navbar-brand" href="<%= root_url %>"/>Home</a>
           <% if logged_in? %>
             <a class="navbar-brand" <%= link_to 'Log Out', logout_path, method: :delete %>"</a>
             <a class="navbar-brand" <%= link_to 'All Courses', courses_path %></a>
             <a class="navbar-brand" <%= link_to 'New Course', new_course_path %></a>
             <a class="navbar-brand" <%= link_to 'New Student', new_student_path %></a>
             <a class="navbar-brand" id="all_students"<%= link_to 'All Students', students_path %></a>
             <!-- <button class="navbar-brand" id="sort_students">  Sort Students</button> -->
             <a class="navbar-brand" id="sort_students">Sort Students</a>
          <% end %>
          </div>
          <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <!--add about info  -->
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>

      <!-- content -->
      <div id="app-container" class="container"  role="main">
        <%= yield %>
      </div>
      <footer class="container-fluid"> <%# Start footer %>
     <small>&copy; 2019 <strong>Gradelink</strong></small>
   </footer> <%# End footer %>

    </body>


</html>